name: Windows app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build app
        run: pyinstaller -w -F main.py

      - name: Upload app to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/app.exe
